name: build
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          # cache: npm

      - name: Install dependencies
        run: npm install --prefer-offline

      - name: Type check
        run: npm run type-check

      - name: Run Jest tests
        run: npm test

      - name: Build
        # run: npm run build -- --public-url https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}
        run: npm run build -- --public-url https://remarkablemark.org/${{ github.event.repository.name }}

      - name: Deploy
        if: github.ref_name == 'master'
        uses: remarkablemark/gitploy-action@v1
        with:
          directory: dist
